name: Build then run CI Chains

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    # Install and setup go
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    # create cache directory
    - name: create upload directory
      run: mkdir -p /tmp/build/

    # build gaiad/gaiacli
    - name: checkout gaia
      uses: actions/checkout@v2
      with:
        repository: cosmos/gaia
        ref: refs/heads/ibc-alpha
    - name: build binary
      run: make build

    # upload gaiacli binary
    - name: upload gaiacli binary
      uses: actions/upload-artifact@v1
      with:
        name: gaiacli-${{ github.sha }}
        path: ./build/gaiacli

    # upload gaiad binary
    - name: upload gaiad binary
      uses: actions/upload-artifact@v1
      with:
        name: gaiad-${{ github.sha }}
        path: ./build/gaiad

    # build relayer
    - name: checkout relayer
      uses: actions/checkout@v2
    - name: build binary and move to upload location
      run: make build

    # upload resulting binaries
    - name: upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: relayer-${{ github.sha }} 
        path: ./build/relayer

  test:
    name: test-liveness
    needs: build
    runs-on: ubuntu-latest
    steps:

    # Make binary directory
    - name: create directory
      run: mkdir -p /tmp/build

    # Checkout gaia to download the binaries
    - name: Checkout gaia
      uses: actions/checkout@v2
      with:
        repository: cosmos/gaia
        ref: refs/heads/ibc-alpha

    # Download gaiad binary
    - name: download gaiad
      uses: actions/download-artifact@v1
      with:
        name: gaiad-${{ github.sha }}  
        path: /tmp/build/gaiad

    # Download gaiacli binary
    - name: download gaiacli
      uses: actions/download-artifact@v1
      with:
        name: gaiacli-${{ github.sha }}  
        path: /tmp/build/gaiacli

    # Checkout the relayer repo
    - name: Checkout relayer
      uses: actions/checkout@v2

    # Download binaries
    - name: download relayer
      uses: actions/download-artifact@v1
      with:
        name: relayer-${{ github.sha }}  
        path: /tmp/build/relayer

    # Run the ci-chains.sh test 
    - name: Run ci-chains check
      run: |
        ./ci-chains.sh

